name: couple_gacha
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.3.0
  m5_fpc1020a:
    path: ../m5_fpc1020a_dart
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: super-malibu
      fonts:
        - asset: fonts/SuperMalibu-Wp77v.ttf
